import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/cms/layout/SideBar";
import Header from "@/components/cms/layout/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
// import "@ant-design/v5-patch-for-react-19";
import theme from "@/config/themeConfig";
// const roboto = Roboto({
//   weight: ["400", "500", "600", "700"], // Optional: choose weights you need
//   subsets: ["latin"], // Optional: choose subsets
//   display: "swap", // Optional: optimize for performance
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={roboto.className}> */}
      <body>
        <ConfigProvider theme={theme}>
          <AntdRegistry>
            <div className="bg-[#F8F9FA]">
              <div className="p-[16px] flex gap-[16px]">
                <div className="">
                  <SideBar />
                </div>

                <main className="flex-1">
                  <div className="flex flex-col  gap-[16px]">
                    <Header />
                    {children}
                  </div>
                </main>
              </div>
            </div>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
