import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App, ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import LayoutBase from "@/components/cms/layout/LayoutBase";
import theme from "@/config/themeConfig";
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={roboto.className + " bg-[#F8F9FA]"}>
        <div className="m-4">
          <ConfigProvider theme={theme}>
            <AntdRegistry>
              <App>
                {/* <LayoutBase>{children}</LayoutBase> */}
                {children}
              </App>
            </AntdRegistry>
          </ConfigProvider>
        </div>
      </body>
    </html>
  );
}
